---
title: 'Create graphs for talk'
author: ""
date: "August 2017"
output:
  html_document:
    toc: yes
---

```{r setup,  include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

---
title: "Contents"
output:
  html_document:
    toc: true
    toc_depth: 1
---


```{r doestim-cum,  echo=T}

read.table('/Users/acristia/Dropbox/_LangTsi/derivedFiles/minTalk_all.txt', header=T)->tsi
tsi$Age.range <- factor(tsi$Age.range)

nwordsxsent=3
nsentxmin=30
hxday=10
daysxmonth=365.25/12

tsicum=sum(tsi[1, "Focal.directed.min.h"] * nsentxmin * nwordsxsent * hxday * daysxmonth * 12 +
             tsi[2, "Focal.directed.min.h"] * nsentxmin * nwordsxsent * hxday * daysxmonth * 12 +
             tsi[3, "Focal.directed.min.h"] * nsentxmin * nwordsxsent * hxday * daysxmonth * 12 +
             tsi[4, "Focal.directed.min.h"] * nsentxmin * nwordsxsent * hxday * daysxmonth * 12 +
             tsi[5, "Focal.directed.min.h"] * nsentxmin * nwordsxsent * hxday * daysxmonth * 24 +
             tsi[6, "Focal.directed.min.h"] * nsentxmin * nwordsxsent * hxday * daysxmonth * 24 +
             tsi[7, "Focal.directed.min.h"] * nsentxmin * nwordsxsent * hxday * daysxmonth * 24 #up to 10y 
             )



#removed  amcum, rurmozcum, mayancum,  dutchcum,
cums=rbind(tsicum,  45 * 10^6 + (45 * 10^6)/3*7, 350 * 10^6)/10^6
#removed "Rural Mzmbq [5]", "Maya [6]", "Dutch Professnl[4]",
rownames(cums)<-c("Tsimane",  "American (high SES)","Supervised SR")
```



```{R dobarplot}
pdf("bars.pdf",height=10,width=4,pointsize=20)
par(mar=c(1, 3, 1, 1))
barplot(t(cums),xlab="",ylab="",xaxt="n",pch="-",yaxt="n",  main="",col="lightgray")
axis(2)
mtext("Millions of words experienced",2,line=2)
text(c(.5,1.8,3.2),c(15,150,350),labels=rownames(cums),cex=1, col=c(rep("red",length(cums)-1),"blue"),srt=90, pos=c(4,4,2))
dev.off()
```



